services:
  # Frontend Static Site
  - type: web
    name: restaurant-ai-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Restaurant Service
  - type: web
    name: restaurant-ai-restaurant-service
    env: python
    buildCommand: pip install -r backend/restaurant-service/requirements.txt
    startCommand: cd backend/restaurant-service && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: CORS_ORIGINS
        value: "https://restaurant-ai-frontend.onrender.com,http://localhost:3000,http://localhost:5173"
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-ai-db
          property: connectionString
      - key: AI_SERVICE_URL
        value: "https://restaurant-ai-ai-service.onrender.com"

  # Menu Service
  - type: web
    name: restaurant-ai-menu-service
    env: python
    buildCommand: pip install -r backend/menu-service/requirements.txt
    startCommand: cd backend/menu-service && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: CORS_ORIGINS
        value: "https://restaurant-ai-frontend.onrender.com,http://localhost:3000,http://localhost:5173"
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-ai-db
          property: connectionString

  # AI Service
  - type: web
    name: restaurant-ai-ai-service
    env: python
    buildCommand: pip install -r backend/ai-service/requirements.txt
    startCommand: cd backend/ai-service && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://restaurant-ai-frontend.onrender.com,http://localhost:3000,http://localhost:5173"
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-ai-db
          property: connectionString

databases:
  - name: restaurant-ai-db
    databaseName: restaurant_ai_db
    user: restaurant_user

  - name: restaurant-ai-redis
    plan: starter