services:
  # Frontend Static Site
  - type: web
    name: restaurant-ai-frontend
    env: static
    buildCommand: |
      cd frontend
      npm ci --production=false
      rm -rf dist
      npm run build
      ls -la dist/
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: GENERATE_SOURCEMAP
        value: false
      - key: VITE_API_BASE_URL
        value: https://restaurant-ai-backend.onrender.com

  # Backend Service
  - type: web
    name: restaurant-ai-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-ai-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: NODE_ENV
        value: production

databases:
  - name: restaurant-ai-db
    databaseName: restaurant_ai_db
    user: restaurant_user
